unidades = {
    0: "zero",
    1: "um",
    2: "dois",
    3: "três",
    4: "quatro",
    5: "cinco",
    6: "seis",
    7: "sete",
    8: "oito",
    9: "nove",
    "0": "zero",
    "1": "um",
    "2": "dois",
    "3": "três",
    "4": "quatro",
    "5": "cinco",
    "6": "seis",
    "7": "sete",
    "8": "oito",
    "9": "nove"
}
dezenas = {
    10: "dez",
    11: "onze",
    12: "doze",
    13: "treze",
    14: "catorze",
    15: "quinze",
    16: "dezesseis",
    17: "dezessete",
    18: "dezoito",
    19: "dezenove",
    20: "vinte",
    30: "trinta",
    40: "quarenta",
    50: "cinquenta",
    60: "sessenta",
    70: "setenta",
    80: "oitenta",
    90: "noventa",
    "10": "dez",
    "11": "onze",
    "12": "doze",
    "13": "treze",
    "14": "catorze",
    "15": "quinze",
    "16": "dezesseis",
    "17": "dezessete",
    "18": "dezoito",
    "19": "dezenove",
    "20": "vinte",
    "30": "trinta",
    "40": "quarenta",
    "50": "cinquenta",
    "60": "sessenta",
    "70": "setenta",
    "80": "oitenta",
    "90": "noventa",
    "2": "vinte",
    "3": "trinta",
    "4": "quarenta",
    "5": "cinquenta",
    "6": "sessenta",
    "7": "setenta",
    "8": "oitenta",
    "9": "noventa",
    2: "vinte",
    3: "trinta",
    4: "quarenta",
    5: "cinquenta",
    6: "sessenta",
    7: "setenta",
    8: "oitenta",
    9: "noventa"
}
centenas = {
    100: "cem",
    200: "duzentos",
    300: "trezentos",
    400: "quatrocentos",
    500: "quinhentos",
    600: "seiscentos",
    700: "setecentos",
    800: "oitocentos",
    900: "novecentos",
    "100": "cem",
    "200": "duzentos",
    "300": "trezentos",
    "400": "quatrocentos",
    "500": "quinhentos",
    "600": "seiscentos",
    "700": "setecentos",
    "800": "oitocentos",
    "900": "novecentos",
    "1": "cento",
    "2": "duzentos",
    "3": "trezentos",
    "4": "quatrocentos",
    "5": "quinhentos",
    "6": "seiscentos",
    "7": "setecentos",
    "8": "oitocentos",
    "9": "novecentos",
    1: "cento",
    2: "duzentos",
    3: "trezentos",
    4: "quatrocentos",
    5: "quinhentos",
    6: "seiscentos",
    7: "setecentos",
    8: "oitocentos",
    9: "novecentos"
}
milhares = {
    1000: "mil",
    2000: "dois mil",
    3000: "três mil",
    4000: "quatro mil",
    5000: "cinco mil",
    6000: "seis mil",
    7000: "sete mil",
    8000: "oito mil",
    9000: "nove mil",
    "1000": "mil",
    "2000": "dois mil",
    "3000": "três mil",
    "4000": "quatro mil",
    "5000": "cinco mil",
    "6000": "seis mil",
    "7000": "sete mil",
    "8000": "oito mil",
    "9000": "nove mil",
    "1": "mil",
    "2": "dois mil",
    "3": "três mil",
    "4": "quatro mil",
    "5": "cinco mil",
    "6": "seis mil",
    "7": "sete mil",
    "8": "oito mil",
    "9": "nove mil",
    1: "mil",
    2: "dois mil",
    3: "três mil",
    4: "quatro mil",
    5: "cinco mil",
    6: "seis mil",
    7: "sete mil",
    8: "oito mil",
    9: "nove mil"
}
